export const FETCH_ISSUES_SUCCEEDED = 'FETCH_ISSUES_SUCCEEDED';
export const GET_ISSUE_SUCCEEDED = 'GET_ISSUE_SUCCEEDED';
export const FETCH_REPO_SUCCEEDED = 'FETCH_REPO_SUCCEEDED';
export const LOADING_START = 'LOADING_START';
export const SET_PAGE = 'CHANGE_PAGE';
